### ISSUE TITLE
Accessing map via primitive does not work

### ISSUE THREAD

**Issue by ethlo** [PebbleTemplates/pebble#196]
Accessing a `java.util.Map<Integer, Integer>` value by primitive value (int) will not return a value.

Expected:
`{{map[1]}}` should work

**Comment by ethlo** [comment]
I see that the `1` is translated to a `java.lang.Long`, and thus the get method of the map will not consider it equal to an `java.lang.Integer` of the same number value.

**Comment by mbosecke** [comment]
You're exactly right, all literal numbers in Pebble are treated as Longs. I suspect it also doesn't work for `Map<Short, ?>` and `Map<Byte,?>` and possibly others. It would only work if your keys happen to be of type `Long`. This is a really tricky problem to solve because it's impossible to know the type of a Map at runtime due to type erasure.

The only solution I can think of at the moment is brute force; cast the Long into every known java primitive type and attempt to look up a value in the map with that type. This is completely insane so I'm going to have to continue to think about it and I'm open to any suggestions.

**Comment by DanStout** [comment]
Well, we may not be able to determine the type of the map itself at runtime, but we can check the type of its keys. Perhaps the check could work like:

- If the map is empty, do nothing
- Else if the key's type is numeric (i.e. `Number.class.isAssignableFrom(key.getClass())` returns true), get the first key in the map, determine its type, and use that to do the conversion
- Else do what is already being done (get using the plain key value)

Little test:
```
public static void main(String[] args)
{
	Map<Integer, String> origMap = new HashMap<>();
	int iIndex = 1;
	long lIndex = 1;
	origMap.put(iIndex, "Test");
	
	Map<?, ?> objMap = origMap;
	
	System.out.println("Map contains int 1: " + objMap.containsKey(iIndex));
	System.out.println("Map contains long 1: " + objMap.containsKey(lIndex));
	
	if (!objMap.isEmpty())
	{
		Set<?> set = objMap.keySet();
		Class<?> keyClass = set.iterator().next().getClass();
		Object cast = cast(lIndex, keyClass);
		System.out.println("Map contains cast 1: " + objMap.containsKey(cast));
	}
}

private static Object cast(Number index, Class<?> desiredType)
{
	if (desiredType == Integer.class)
	{
		return index.intValue();
	}
	else if (desiredType == Byte.class)
	{
		return index.byteValue();
	}
	// Todo: Other types
	return null;
}
```

Outputs:
```
Map contains int 1: true
Map contains long 1: false
Map contains cast 1: true
```

For reference, `GetAttributeExpression` currently works like so:
```
if (object instanceof Map && ((Map<?, ?>) object).containsKey(attributeNameValue)) {
	return ((Map<?, ?>) object).get(attributeNameValue);
}
```

**Comment by ebussieres** [comment]
Just commited a fix for this

**Comment by ethlo** [comment]
Nice work!
