### ISSUE TITLE
Is it dying?

### ISSUE THREAD

**Issue by decebals** [PebbleTemplates/pebble#311]
Hi,

I see no activities (interest) for this project in the last period of time? They are many PR and issues with no resolution or comment. 
@mbosecke Do you intent to continue working on this project? Any information from maintainers about the next steps/releases is very welcome.

**Comment by DirkLachowski** [comment]
Ping.

**Comment by deelo55** [comment]
Seems pretty dead...

**Comment by hectorlf** [comment]
Sorry, for the delay, guys. Mitchell has some IRL things to attend to, so Eric and I will try to do some of the housekeeping. Please be patient, as we are just the reserves.

**Comment by hectorlf** [comment]
Not me, that's for sure.

**Comment by DirkLachowski** [comment]
@hectorlf Hey hector, glad you have stepped in. Just to understand you right: Is this a confirmation that the project is not dying but that it's only a resource problem (i would be fine with that) or will a new maintainer be needed sometime?

**Comment by deelo55** [comment]
Given there has been no response on this for over 3 months I assume that it is actually dying. Should we fork the project? Is anyone interested in maintaining this?

**Comment by hc-codersatlas** [comment]
Would be happy to fork / maintain this. We use it for quite a few private projects. Anyone else interested?

**Comment by cjbrooks12** [comment]
I would be interested in helping maintain a fork with you @hc-codersatlas, @deelo55. I've been using Pebble as the main template engine in my new static site generator, [Orchid](https://github.com/JavaEden/Orchid), and the future of Pebble is pretty important for its success. 

I've gone ahead a set up a fork under Orchid's organization and would love to host the new fork there indefinitely. I will invite anyone who wishes to be an admin in that project, and will get it set up to release to Bintray as well (under a different groupId, obviously).

https://github.com/JavaEden/pebble

**Comment by cjbrooks12** [comment]
Alright, I've now got Pebble moved over to my organization @JavaEden and set up on Bintray, with Maven Central coming soon (see checklist below for status). I will go through all the open PRs and request they be moved to the new repo. Please take new issues there as well. In addition, I would like to pick back up discussions around releasing Pebble 3.0, and welcome you all to join the conversation on Gitter. 

**Links**
- https://github.com/JavaEden/pebble
- https://bintray.com/javaeden/Eden/Pebble
- https://gitter.im/JavaEden/pebble

**Maven Central Checklist**
- [ ] Project needs to be synced to jCenter
- [ ] Domain needs to finish getting set up, so I can create the groupId on Sonatype
- [ ] Create groupId on Sonatype
- [ ] Group is approved on Sonatype 
- [ ] Artifacts published to Maven Central

**Comment by hectorlf** [comment]
This is pretty infuriating. Let me remind you that the project you are forking has a copyright, and uses Mitchel's private namespace. If you are to continue this hostile fork, make sure to pick a new name, new namespace, and repackage all the classes.

Ah, the joys of open source software.

**Comment by deelo55** [comment]
What’s infuriating? No one seems to be working on this anymore....last commit was 7 months ago.


________________________________

**Comment by deelo55** [comment]
“Respect the owners decisions”  - sorry I’m not clear what the owners decisions are given that he has not replied to any issues for several months or made clear what his intentions are. 

My only interest is seeing this project improve and I think that is the aim of the community. There are many unanswered threads in the forum and no commits for several months. This is not the way to encourage the community to support this project. 

Ideally I would love to see work continue on this project and I have even said I’m willing to pay for work on this yet there has been no interest from anyone or even a comment from the owner in months. 

Given that no progress appears  to be made on this project I would support a fork unless I hear otherwise from the owner or I see some commits to the project.

**Comment by ebussieres** [comment]
Hi everybody,

I want to reassure everybody Pebble isn't dying. We did lack a lot of focus on this project but we invest our own time in this for free. We have family to take care of too

Focus for now should be to release v3. So I suggest everyone to submit PR in order to have a v3 as soon as possible. We're gonna check those PR I assure you. Meantime, I'm gonna do a cleanup of existing PR, issues and recheck what was in 3.0 branch

Thank you all for your understanding and your commitment to this wonderful project

**Comment by hectorlf** [comment]
Small big update:

As you might know, Maven Central requires a private key to guarantee authenticity of artifacts. @ebussieres has tried to reach Mitchell to get this info, without much success. Pebble is published using Mitchell's personal namespace, so, even if we got a hold on the keys, it feels a bit wrong... So, given the circumstances, we think it's better to pick a new group id that's only tied to this project, and for that we need a new name. Naming things is hard, so we'd appreciate your ideas.

Let me start with one suggestion:

io.pebbletemplateengine

BTW, the package names don't need to change, at least for the moment.

**Comment by cjbrooks12** [comment]
I would vote for `com.pebbletemplates` or `io.pebbletemplates`, to match the Github organization name. MavenCentral requires ownership of the domain used for the groupId, which would mean purchasing the corresponding domain, or using one like `io.github.pebbletemplates`. 

That being said, what would be the impact of publishing artifacts _only_ on JCenter? It is much, much easier to publish and manage on Bintray, and removes some of the restrictions like owning the domain for the groupId.

**Comment by slandelle** [comment]
@cjbrooks12 central is enabled by default on all jvm build tools, on contrary to jcenter.

**Comment by cjbrooks12** [comment]
Yes, MavenCentral might be the default, but every build tool should allow the addition of custom Maven coordinates, which means they can all use JCenter. JCenter is a superset of MavenCentral, so there shouldn't be any issues with anyone using JCenter instead of MavenCentral, and it is easy enough to add in the docs how to set up the project to use JCenter.

I'm just thinking that using Bintray for managing released artifacts will free Pebble from ultimately relying on a single maintainer, as we can have Bintray host and GPG sign artifacts for us and no one has to manage deploy keys. 

Of course, I may be wrong and it is possible someone may have had issues using JCenter, and I think it would be good to know if anyone has actually experienced issues using JCenter. But as it is I've never heard of anyone having issues, and I think Pebble could benefit from moving to JCenter. Keeping artifacts on MavenCentral just because that's the way it is always been doesn't strike me as a terribly compelling reason.

**Comment by hectorlf** [comment]
Don't worry about registrations or organisation names, just pick a name you like!

Another reason for central: it's already there :-/

**Comment by hectorlf** [comment]
IMHO, that's not compelling either. If the deal are the tools, we'll have to find the tools.

**Comment by slandelle** [comment]
Yes, as an sbt user (where they tried to make JCenter the default), I’ve had issues with JCenter several times in the past.
My point is that pulling from central doesn’t require any extra conf. And sync’ing from JCenter to central is built in.

**Comment by ebussieres** [comment]
My vote goes to something matching the pebble organization name. Anyone has other suggestions/ideas ?

**Comment by hectorlf** [comment]
Should we end the poll already?

**Comment by hc-codersatlas** [comment]
Let's match the organization name and move on?

**Comment by hectorlf** [comment]
Done: http://pebbletemplates.io

There's a temporary redirect set up while we think what to do next with the web.

**Comment by ebussieres** [comment]
Good news ! We're closer to a new release !

**Comment by ebussieres** [comment]
Just released v2.5.0 😁

**Comment by slandelle** [comment]
@ebussieres Thanks for your great work!

**Comment by ebussieres** [comment]
Thanks to @hectorlf too ! He did a terrific job

**Comment by cjbrooks12** [comment]
Great work guys, I'm trying out the new release right now!
