### ISSUE TITLE
Add attribute/variable in template while parsing

### ISSUE THREAD

**Issue by isoubelet** [PebbleTemplates/pebble#347]
Hi there,
I am trying to process some "variables" in my template, by writing custom functions. I would need the result of that function available later in the template as if I put it in the context.

An example:
`{{ model.addAttribute("MyVarName", myFunction()) }}`

Since I am using Spring, Model refers to org.springframework.ui.Model.

So far so good, but the problem comes when I try to use that variable later in the template, as follows:
`{{ MyVarName }}`

Pebble does not recognize it...
Any clue? Is there a better way/pattern to face this?

Thanks guys!

**Comment by cjbrooks12** [comment]
You can use the [`set` tag](http://www.mitchellbosecke.com/pebble/documentation/tag/set) to assign the function value to a new variable in the local scope.

```jinja
{% set MyVarName = myFunction() %}
{{ MyVarName }}
```

Adding the attribute as you have done should work fine since it's just calling a method on the model. In this case, you just need to reference the new variable from the model and not from the root scope.

```jinja
{{ model.addAttribute("MyVarName", myFunction()) }}
{{ model.MyVarName }}
```

That is assuming that the implementation of `org.springframework.ui.Model` is actually a `Map` (which it looks like it is according to its Javadocs).

**Comment by isoubelet** [comment]
Excellent, Casey. That's what I was looking for.
Just one thing, in Spring Boot, when you're in a Controller context, Model acts as a container of attributes for templates. 
In fact, all the elements stored in there can be referenced in Pebble using just the attribute name. That's why I thought that, by adding a new element in the template, I could use that element later in the same template.

Many thanks!
