### ISSUE TITLE
Using an unmodifiable map as context causes errors while evaluating the template

### ISSUE THREAD

**Issue by hex-agon** [PebbleTemplates/pebble#449]
Currently i'm using pebble with [javalin](https://javalin.io/) and by default, when not specifying a context map, javalin passes a `emptyMap()` to pebble and this causes an `UnsupportedOperationException` to be thrown:
```
java.lang.UnsupportedOperationException: Operation is not supported for read-only collection
	at kotlin.collections.EmptyMap.put(Maps.kt) ~[kotlin-stdlib-1.3.31.jar:1.3.31-release-198 (1.3.31)]
	at com.mitchellbosecke.pebble.template.Scope.put(Scope.java:68) ~[pebble-3.0.10.jar:?]
	at com.mitchellbosecke.pebble.template.ScopeChain.put(ScopeChain.java:96) ~[pebble-3.0.10.jar:?]
	at com.mitchellbosecke.pebble.template.ScopeChain.set(ScopeChain.java:228) ~[pebble-3.0.10.jar:?]
	at com.mitchellbosecke.pebble.node.SetNode.render(SetNode.java:31) ~[pebble-3.0.10.jar:?]
	at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:43) ~[pebble-3.0.10.jar:?]
	at com.mitchellbosecke.pebble.node.RootNode.render(RootNode.java:30) ~[pebble-3.0.10.jar:?]
	at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:149) ~[pebble-3.0.10.jar:?]
	at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:92) ~[pebble-3.0.10.jar:?]
	at io.javalin.plugin.rendering.template.JavalinPebble.render(JavalinPebble.kt:31) ~[javalin-3.1.0.jar:?]
	at io.javalin.plugin.rendering.JavalinRenderer.renderBasedOnExtension(JavalinRenderer.kt:33) ~[javalin-3.1.0.jar:?]
	at io.javalin.http.Context.render(Context.kt:440) ~[javalin-3.1.0.jar:?]
	at io.javalin.http.Context.render$default(Context.kt:439) ~[javalin-3.1.0.jar:?]
	at io.javalin.http.Context.render(Context.kt) ~[javalin-3.1.0.jar:?]
```

I took a look at pebble's source and it seems that pebble reuses that context map to render a few tags. I did [open an issue with javalin](https://github.com/tipsy/javalin/issues/644) but i feel like that this is something that should be solved on pebble's side by making a defensive copy of the supplied map before adding it to the scope. Is this something that can be done or is there any special reason why this behaviour exists?

**Comment by slandelle** [comment]
Not fond of the defensive copy that would cause extra allocations. I'd be more in favor of explaining context is not read-only and per rendering.

**Comment by cjbrooks12** [comment]
I think I'm with @slandelle, too, this shouldn't be a concern of Pebble. A Context map shouldn't be reused across renders, so Pebble should be able to assume the context given is isolated and safe to write to directly. 

Also, the issue is more of a Kotlin-specific issue, where `Map<>` in Java is mutable while it is immutable in Kotlin. The Java API here assumes that Pebble is given a mutable map (because Maps are mutable by default), so it's the Kotlin end that's breaking the contract by passing in an immutable context map by default.

**Comment by tipsy** [comment]
> I think I'm with @slandelle, too, this shouldn't be a concern of Pebble. A Context map shouldn't be reused across renders, so Pebble should be able to assume the context given is isolated and safe to write to directly.

Sorry for butting in here. Ultimately it's up to you as the maintainers, but I don't think an API should make assumptions and fail hard. You could check if the map is immutable, then either make a defensive copy, or throw an exception.

> Also, the issue is more of a Kotlin-specific issue, where Map<> in Java is mutable while it is immutable in Kotlin. The Java API here assumes that Pebble is given a mutable map (because Maps are mutable by default), so it's the Kotlin end that's breaking the contract by passing in an immutable context map by default.

The Java 9 factory method (`Map.of()`) produces immutable maps. A lot of people are moving towards immutable data structures, and especially mutating an argument is considered bad practice. I understand that some people may want it for performance reasons, but maybe it could be a setting on the engine rather than the default?

**Comment by slandelle** [comment]
> You could check if the map is immutable

How would you do that? Java doesn’t have 2 distinct APIs for mutable vs mutable, on contrary to Scala.

**Comment by tipsy** [comment]
I guess you could be dealing with any number of variations of immutable maps (Java, Kotlin, Guava, etc), so something as silly as a `try` ?

```java
isMutable(Map<String, Object> map) {
    try {
        map.put(UUID.randomUUID().toString(), true)
        return true;
    } catch (Exception e) {
        return false;
    }
}
```

**Comment by slandelle** [comment]
Exceptions for flow control are really not performant.
Honestly, I don’t think Java provides a proper solution for this, because it wasn’t designed this way.

**Comment by hex-agon** [comment]
As it seems this is an intended behaviour i'll mark this issue as solved.

**Comment by cjbrooks12** [comment]
In looking through the codebase, it looks like the provided context map just gets pushed into the ScopeChain when a template is evaluated. I'm thinking that if we push a mutable map into the chain right after it, then the original map can stay immutable while templates would be able to mutable the context as needed. I'll try this out tonight to see if it works, it might be a good solution that shouldn't impact performance much.
