### ISSUE TITLE
Pass _context and _self as apply() arguments rather than as args' values

### ISSUE THREAD

**Issue by hectorlf** [PebbleTemplates/pebble#64]
It would be very handy to not have to track arguments that are external to Filter/Function actual parameters, given that this two are always present. Handling of multi-arg functions, in particular, would benefit. The downside is it breaks compatibility.

**Comment by mbosecke** [comment]
Unfortunately breaking backwards compatibility at this point is not an option; I know there are a lot of custom extensions out there. I'll keep it in mind for a possible version 2.0 of pebble (which I haven't begun development on). 

In the meantime if by "multi-arg" functions you mean functions that accepts an unknown or unlimited amount of arguments I suggest using the built-in [min](https://github.com/mbosecke/pebble/blob/master/src/main/java/com/mitchellbosecke/pebble/extension/core/MinFunction.java) or [max](https://github.com/mbosecke/pebble/blob/master/src/main/java/com/mitchellbosecke/pebble/extension/core/MaxFunction.java) functions as reference. They use an integer as a key to pull out arguments from the argument map which will effectively ignore the "_self" and "_context" keys.

Otherwise, if by "multi-arg" functions you mean functions that accept more than one argument but you still know exactly how many, I suggest giving them all names, such as I do in the built-in [i18n](https://github.com/mbosecke/pebble/blob/master/src/main/java/com/mitchellbosecke/pebble/extension/i18n/i18nFunction.java) function.

**Comment by hectorlf** [comment]
That's understandable. I'll close this for now, then.

**Comment by hectorlf** [comment]
Am I late to beg you to reconsider this now that 2.0 breaks backcompat??

**Comment by mbosecke** [comment]
Implemented on the 3.0 branch
